import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const base=process.env.STUDIO_TEST_URL||'http://127.0.0.1:8897';assert.notEqual(new URL(base).port,'8877');
const browser=await chromium.launch({headless:true,executablePath:process.env.STUDIO_CHROMIUM});
const page=await browser.newPage({viewport:{width:1600,height:900}});const errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&r.url().includes('/api/'))errors.push(r.status()+' '+r.url());});
try {
 await page.goto(base+'/#home');await page.locator('.new-project-tile').click();
 const nav=page.getByRole('navigation',{name:'Main navigation'});
 assert.equal(await nav.getByRole('button',{name:'GPT',exact:true}).count(),1);
 assert.equal(await nav.getByRole('button',{name:'PaitonMail',exact:true}).count(),0);
 await nav.getByRole('button',{name:'MCP Servers',exact:true}).click();
 await page.getByRole('heading',{name:'MCP Servers',exact:true}).waitFor();
 await page.getByRole('button',{name:'Configure Mail'}).click();
 await page.getByRole('heading',{name:'Mail MCP server'}).waitFor();
 assert.equal(await page.locator('.mail-inbox,.mail-reader').count(),0);
 await page.getByRole('button',{name:'Enable MCP server',exact:true}).click();
 await page.getByText('MCP enabled',{exact:true}).waitFor();
 const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('link',{name:'Download client configuration'}).click()]);
 assert.equal(download.suggestedFilename(),'paiton-studio-mcp.json');
 await page.getByRole('button',{name:'Show configuration'}).click();await page.locator('.mcp-client-config pre').waitFor();
 assert.ok((await page.locator('.mcp-client-config pre').innerText()).includes('Bearer '));
 await page.getByRole('button',{name:'Hide token'}).click();
 await page.getByText('Configure SMTP',{exact:true}).click();
 await page.getByLabel('SMTP server',{exact:true}).fill('smtp.example.org');
 await page.getByLabel('From address',{exact:true}).fill('studio@example.org');
 await page.getByLabel('Username',{exact:true}).fill('studio');
 await page.getByLabel('App password',{exact:true}).fill('browser-fixture-only');
 await page.getByRole('button',{name:'Save SMTP settings'}).click();
 await page.getByText('SMTP configured',{exact:true}).waitFor();
 assert.equal(await page.getByLabel('App password',{exact:true}).inputValue(),'');
 await page.reload();await page.getByRole('button',{name:'Configure Mail'}).click();await page.getByText('SMTP configured',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Disconnect SMTP',exact:true}).click();await page.getByText('Not configured',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Disable connection'}).click();await page.getByText('MCP disabled',{exact:true}).waitFor();
 await page.goto(base+'/#mail');await page.reload();await page.getByRole('heading',{name:'MCP Servers',exact:true}).waitFor();assert.equal(new URL(page.url()).hash,'#mcp');
 await page.locator('.mcp-starters .mcp-server-card').filter({has:page.getByRole('heading',{name:'Document briefing',exact:true})}).getByRole('button',{name:'Build this server'}).click();
 await page.getByRole('heading',{name:'Create your MCP server'}).waitFor();
 assert.equal(await page.getByLabel('Agent name',{exact:true}).inputValue(),'Document briefing');
 await page.getByLabel('Agent name',{exact:true}).fill('My document MCP');
 await page.getByRole('button',{name:'Create MCP server',exact:true}).click();
 await page.getByRole('button',{name:'Configure MCP server',exact:true}).click();
 await page.getByRole('heading',{name:'My document MCP',exact:true}).waitFor();
 await page.getByText('Server disabled',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Enable MCP server',exact:true}).click();
 await page.getByText('Server enabled',{exact:true}).waitFor();
 const [agentConfig]=await Promise.all([page.waitForEvent('download'),page.getByRole('link',{name:'Download client configuration'}).click()]);
 assert.equal(agentConfig.suggestedFilename(),'paiton-agent-mcp.json');
 await page.getByRole('button',{name:'Show configuration'}).click();
 assert.ok((await page.locator('.mcp-client-config pre').innerText()).includes('/mcp/agents/'));
 await page.getByRole('button',{name:'Disable server',exact:true}).click();
 await page.getByText('Server disabled',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Open agent',exact:true}).click();
 await page.locator('.agent-desk').getByRole('heading',{name:'My document MCP',exact:true}).waitFor();
 await nav.getByRole('button',{name:'MCP Servers',exact:true}).click();
 await page.getByRole('button',{name:'All MCP servers'}).click();
 await page.getByRole('heading',{name:'My document MCP',exact:true}).waitFor();
 await page.reload();
 await page.getByRole('heading',{name:'My document MCP',exact:true}).waitFor();
 assert.equal(await page.locator('.mcp-server-card').filter({has:page.getByRole('heading',{name:'Mail MCP server',exact:true})}).count(),1);
 await page.screenshot({path:'.local/mcp-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.screenshot({path:'.local/mcp-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('MCP UI passed: collection, starter → agent → server, persistence, enable/config/revoke, SMTP preservation, responsive layout and no console/API errors.');
}finally{await browser.close();}
